const colors = {
  light: {
    text: "#0A0A0F",
    tint: "#6C5CE7",
    background: "#F5F5FA",
    foreground: "#0A0A0F",
    card: "#FFFFFF",
    cardForeground: "#0A0A0F",
    primary: "#6C5CE7",
    primaryForeground: "#FFFFFF",
    secondary: "#EEEEF9",
    secondaryForeground: "#0A0A0F",
    muted: "#EEEEF9",
    mutedForeground: "#6E6D7A",
    accent: "#00B894",
    accentForeground: "#FFFFFF",
    destructive: "#FF4757",
    destructiveForeground: "#FFFFFF",
    border: "#E4E4F0",
    input: "#EEEEF9",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#8B7CF6",
    background: "#09090E",
    foreground: "#FFFFFF",
    card: "#14141C",
    cardForeground: "#FFFFFF",
    primary: "#6C5CE7",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1C28",
    secondaryForeground: "#FFFFFF",
    muted: "#1C1C28",
    mutedForeground: "#8A8A9E",
    accent: "#00D2A0",
    accentForeground: "#09090E",
    destructive: "#FF4757",
    destructiveForeground: "#FFFFFF",
    border: "#242434",
    input: "#1C1C28",
  },
  radius: 16,
};

export default colors;
